# Generated by Django 4.0.4 on 2022-05-17 09:24

from django.db import migrations, models
import django.db.models.deletion
import quanly.models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_vaitro_user_vai_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datve',
            name='chuyen_xe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_dat_ve', to='quanly.chuyenxe'),
        ),
        migrations.AlterField(
            model_name='datve',
            name='so_luong_ve',
            field=models.SmallIntegerField(default=1, validators=[quanly.models.validate_gt0]),
        ),
        migrations.AlterField(
            model_name='user',
            name='vai_tro',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_query_name='vaitro', to='quanly.vaitro'),
        ),
    ]
